import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import './style.css';

const ELEMENTS = {
  fire: {
    id:'fire', number:'01', title:'Fire', category:'THE TRANSFORMER', subtitle:'THE FIRST SPARK',
    description:'A force that consumes and creates in the same breath. Fire is change made visible — restless, radiant, impossible to hold.',
    essence:'TRANSFORMATION', polarity:'EXPANSIVE', state:'INCANDESCENT', signature:'EMBER / 01',
    quote:'“From stillness, a spark.”', caption:'A LIVING FLAME · FORM IN MOTION', color:'#ff7540', colorRgb:[1.0,.24,.045], glow:'#ff683a',
  },
  air: {
    id:'air', number:'02', title:'Air', category:'THE CATALYST', subtitle:'THE INVISIBLE CURRENT',
    description:'The unseen architecture between all things. Air carries the whisper, bends the branch and turns emptiness into motion.',
    essence:'MOVEMENT', polarity:'ASCENDING', state:'VAPOROUS', signature:'ZEPHYR / 02',
    quote:'“The unseen gives shape.”', caption:'A CURRENT WITHOUT EDGES · FORM IN MOTION', color:'#a6e8e6', colorRgb:[.32,.91,.91], glow:'#78d9e3',
  },
  water: {
    id:'water', number:'03', title:'Water', category:'THE REMEMBERER', subtitle:'THE DEEP BLUE',
    description:'A patient force with no fixed shape. Water remembers every contour it touches, then carves a path through stone.',
    essence:'ADAPTATION', polarity:'RECEPTIVE', state:'FLUID', signature:'TIDELINE / 03',
    quote:'“Stillness holds a thousand tides.”', caption:'A WORLD HELD IN SUSPENSION · FORM IN MOTION', color:'#51ccf5', colorRgb:[.12,.66,1.0], glow:'#31bce8',
  },
  earth: {
    id:'earth', number:'04', title:'Earth', category:'THE FOUNDATION', subtitle:'THE PATIENT ROOT',
    description:'The quiet weight beneath becoming. Earth gathers the fragments, shelters the seed and gives every journey a place to begin.',
    essence:'ENDURANCE', polarity:'GROUNDED', state:'MINERAL', signature:'BEDROCK / 04',
    quote:'“All returns to ground.”', caption:'AN ANCIENT HEART · FORM IN MOTION', color:'#c1a276', colorRgb:[.59,.82,.47], glow:'#9ea866',
  }
};
const ORDER=Object.keys(ELEMENTS);
const root=document.documentElement;
const canvas=document.querySelector('#scene');
const scene=new THREE.Scene();
scene.background=new THREE.Color('#090b10');
scene.fog=new THREE.FogExp2('#090b10',.035);
const camera=new THREE.PerspectiveCamera(35,1,.1,80);
camera.position.set(0,2.05,8.25);
camera.lookAt(0,1.55,0);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.8));
renderer.outputColorSpace=THREE.SRGBColorSpace;
renderer.toneMapping=THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure=1.22;
renderer.shadowMap.enabled=true;
renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const composer=new EffectComposer(renderer);
composer.addPass(new RenderPass(scene,camera));
const bloom=new UnrealBloomPass(new THREE.Vector2(1,1),.11,.16,.72);
composer.addPass(bloom);
composer.addPass(new OutputPass());

const ambient=new THREE.HemisphereLight(0xa8c0d0,0x16100b,1.25);scene.add(ambient);
const key=new THREE.DirectionalLight(0xffdfc1,3.15);key.position.set(-3,6,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.near=.1;key.shadow.camera.far=16;key.shadow.bias=-.0002;scene.add(key);
const fill=new THREE.PointLight(0x5c9cae,32,12,2);fill.position.set(3,2.8,-1.5);scene.add(fill);
const rim=new THREE.PointLight(0x607989,24,11,2);rim.position.set(-3,2,-3);scene.add(rim);
const elementLight=new THREE.PointLight(0xff683a,6,4.5,2);elementLight.position.set(0,1.9,1);scene.add(elementLight);

const floor=new THREE.Mesh(new THREE.CircleGeometry(14,96),new THREE.MeshStandardMaterial({color:0x101216,roughness:.78,metalness:.2}));floor.rotation.x=-Math.PI/2;floor.position.y=-.025;floor.receiveShadow=true;scene.add(floor);
const haloFloor=new THREE.Mesh(new THREE.CircleGeometry(5.7,96),new THREE.MeshBasicMaterial({color:0x1c2025,transparent:true,opacity:.15,side:THREE.DoubleSide}));haloFloor.rotation.x=-Math.PI/2;haloFloor.position.y=-.018;scene.add(haloFloor);
for(let i=0;i<4;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.62+i*.56,.003,4,128),new THREE.MeshBasicMaterial({color:0xb9c0c0,transparent:true,opacity:.11-i*.018}));ring.rotation.x=-Math.PI/2;ring.position.y=-.009+i*.0005;ring.scale.set(1.35,1,1);scene.add(ring);}
function cylinder(radiusTop,radiusBottom,height,y,color,metalness=.72){const m=new THREE.Mesh(new THREE.CylinderGeometry(radiusTop,radiusBottom,height,96),new THREE.MeshStandardMaterial({color,metalness,roughness:.32}));m.position.y=y;m.castShadow=true;m.receiveShadow=true;scene.add(m);return m;}
cylinder(.84,.94,.15,.11,0x25282a);cylinder(.69,.84,.13,.245,0x15191b);cylinder(.57,.69,.075,.347,0x323439,.8);
const plinthEdge=new THREE.Mesh(new THREE.TorusGeometry(.69,.012,8,100),new THREE.MeshBasicMaterial({color:0x777c7e,transparent:true,opacity:.48}));plinthEdge.rotation.x=Math.PI/2;plinthEdge.position.y=.303;scene.add(plinthEdge);
const plinthTop=new THREE.Mesh(new THREE.CylinderGeometry(.56,.60,.035,80),new THREE.MeshStandardMaterial({color:0x1b1e20,metalness:.7,roughness:.26}));plinthTop.position.y=.399;plinthTop.receiveShadow=true;scene.add(plinthTop);

function makeStars(){const count=520,pos=new Float32Array(count*3),sizes=new Float32Array(count);for(let i=0;i<count;i++){const radius=THREE.MathUtils.randFloat(7,22),theta=Math.random()*Math.PI*2,phi=Math.acos(THREE.MathUtils.randFloatSpread(2));pos[i*3]=radius*Math.sin(phi)*Math.cos(theta);pos[i*3+1]=radius*Math.cos(phi)+2;pos[i*3+2]=radius*Math.sin(phi)*Math.sin(theta)-7;sizes[i]=THREE.MathUtils.randFloat(.012,.034);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));geo.setAttribute('aSize',new THREE.BufferAttribute(sizes,1));const mat=new THREE.PointsMaterial({color:0x94a2ac,size:.022,transparent:true,opacity:.48,sizeAttenuation:true,depthWrite:false});const pts=new THREE.Points(geo,mat);scene.add(pts);return pts;}
const stars=makeStars();

function flameGeometry(height,width,phase){const radial=36,vertical=40,verts=[],uv=[],indices=[];for(let y=0;y<=vertical;y++){const t=y/vertical;const profile=(.24+.76*Math.sin(Math.PI*Math.pow(t,.72)))*Math.pow(1-t,.42);for(let x=0;x<=radial;x++){const u=x/radial,angle=u*Math.PI*2,r=width*profile;const shift=Math.sin(t*5.7+phase)*t*width*.48;verts.push(Math.cos(angle)*r+shift,t*height,Math.sin(angle)*r+Math.cos(t*4+phase)*t*width*.2);uv.push(u,t);}}for(let y=0;y<vertical;y++)for(let x=0;x<radial;x++){const a=y*(radial+1)+x,b=a+radial+1;indices.push(a,b,a+1,b,b+1,a+1);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();return g;}
const flameVertex=`uniform float uTime;varying vec2 vUv;varying vec3 vPos;void main(){vUv=uv;vec3 p=position;float f=vUv.y;p.x+=sin(uTime*2.1+p.y*4.8+vUv.x*9.0)*f*.12;p.z+=cos(uTime*1.6+p.y*5.3+vUv.x*7.0)*f*.09;p.y+=sin(uTime*3.0+vUv.x*8.0+vUv.y*7.0)*f*.035;vPos=p;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}`;
const flameFragment=`uniform float uTime;uniform vec3 uColor;varying vec2 vUv;varying vec3 vPos;void main(){float edge=pow(max(sin(vUv.x*3.14159265),0.0),.55);float tip=1.0-smoothstep(.48,1.0,vUv.y);float core=1.0-smoothstep(.03,.48,vUv.y);float flicker=.88+.12*sin(uTime*6.0+vUv.x*20.0+vUv.y*16.0);vec3 deep=vec3(.48,.018,.003);vec3 orange=vec3(1.0,.115,.006);vec3 gold=vec3(1.0,.52,.045);vec3 col=mix(deep,orange,smoothstep(.05,.62,vUv.y));col=mix(col,gold,pow(tip,1.8)*.9);col=mix(col,vec3(1.0,.94,.62),core*.32);float alpha=edge*(.62-vUv.y*.2)*flicker;gl_FragColor=vec4(col*(.78+tip*.2),alpha);}`;
function addFlame(group,x,z,scale,phase){const mat=new THREE.ShaderMaterial({uniforms:{uTime:{value:0},uColor:{value:new THREE.Color('#ff7540')}},vertexShader:flameVertex,fragmentShader:flameFragment,transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.NormalBlending});const mesh=new THREE.Mesh(flameGeometry(2.45,.48,phase),mat);mesh.position.set(x,.49,z);mesh.scale.setScalar(scale);group.add(mesh);animationMaterials.push(mat);return mesh;}
function addFire(group){addFlame(group,0,-.12,1,0);addFlame(group,-.36,.03,.82,2.1);addFlame(group,.34,.08,.86,4.2);addFlame(group,.05,-.19,.59,5.4);const core=new THREE.Mesh(new THREE.SphereGeometry(.35,48,40),new THREE.MeshPhysicalMaterial({color:0xff7210,emissive:0xb72b00,emissiveIntensity:.85,roughness:.2,metalness:.05,clearcoat:.85,clearcoatRoughness:.15}));core.position.set(0,1.03,0);core.scale.set(.82,1.08,.82);core.castShadow=true;group.add(core);const inner=new THREE.Mesh(new THREE.SphereGeometry(.105,32,24),new THREE.MeshBasicMaterial({color:0xffcf4d}));inner.position.copy(core.position);group.add(inner);}
function tube(points,radius,material,group,segments=140){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)));const mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,segments,radius,8,false),material);group.add(mesh);return mesh;}
function addAir(group){const haze=new THREE.Mesh(new THREE.SphereGeometry(.56,48,36),new THREE.MeshPhysicalMaterial({color:0x7bc6cd,transparent:true,opacity:.085,roughness:.08,metalness:.2,side:THREE.DoubleSide,depthWrite:false}));haze.position.y=1.86;group.add(haze);const center=new THREE.Mesh(new THREE.SphereGeometry(.12,24,20),new THREE.MeshBasicMaterial({color:0xcafff5}));center.position.y=1.86;group.add(center);for(let j=0;j<5;j++){const pts=[];for(let i=0;i<=120;i++){const t=i/120,a=t*Math.PI*3.2+j*1.25,r=.38+t*.72, y=.8+t*2.05;pts.push([Math.cos(a)*r,y,Math.sin(a)*r*.72]);}const material=new THREE.MeshBasicMaterial({color:j%2?0x8bcdd2:0xc1f6eb,transparent:true,opacity:j===0?.76:.46,blending:THREE.AdditiveBlending,depthWrite:false});const strand=tube(pts,j===0?.017:.011,material,group,160);strand.userData.spin=(j%2?.08:-.1);}
for(let i=0;i<3;i++){const orbit=new THREE.Mesh(new THREE.TorusGeometry(.82+i*.12,.007,6,120),new THREE.MeshBasicMaterial({color:0xa9e9e2,transparent:true,opacity:.3,blending:THREE.AdditiveBlending}));orbit.position.y=1.8+(i-1)*.31;orbit.rotation.set(.7+i*.19,.3+i*1.4,.18);group.add(orbit);orbit.userData.spin=.13*(i%2?1:-1);}}
const waterVertex=`uniform float uTime;varying vec3 vNormal;varying vec3 vView;varying vec3 vPos;varying vec2 vUv;void main(){vUv=uv;vec3 p=position;float wave=sin(p.x*5.0+uTime*1.35)*sin(p.y*4.0-uTime*1.08)*sin(p.z*5.0+uTime*.8)*.027;wave+=sin(p.x*10.0-uTime*.75+p.z*8.0)*.009;p+=normal*wave;vec4 mv=modelViewMatrix*vec4(p,1.0);vPos=mv.xyz;vView=normalize(-mv.xyz);vNormal=normalize(normalMatrix*normal);gl_Position=projectionMatrix*mv;}`;
const waterFragment=`uniform float uTime;uniform vec3 uColor;varying vec3 vNormal;varying vec3 vView;varying vec3 vPos;varying vec2 vUv;void main(){vec3 n=normalize(vNormal);float fres=pow(1.0-max(dot(n,normalize(vView)),0.0),3.0);float flow=sin(vPos.y*5.0+uTime*1.4+sin(vPos.x*5.0+uTime)*.55)*.5+.5;float w1=sin(vPos.x*12.0+sin(vPos.y*9.0+uTime)*2.3+uTime+vPos.z*4.0);float w2=sin(vPos.z*15.0-vPos.y*7.0+uTime*1.4);float caustic=pow(max(w1*w2,0.0),7.0);float ribbon=pow(max(sin(vPos.x*8.0+sin(vPos.z*6.0+uTime)*1.4-vPos.y*5.0+uTime*.7)*.5+.5,0.0),13.0);vec3 deep=vec3(.004,.035,.09);vec3 mid=vec3(.008,.20,.35);vec3 light=vec3(.17,.76,.94);vec3 col=mix(deep,mid,clamp(smoothstep(-.75,.6,n.y)*.52+flow*.22,0.0,1.0));col=mix(col,light,fres*.66);col+=light*(caustic*.72+ribbon*.38);col+=pow(flow,5.0)*vec3(.02,.16,.24);gl_FragColor=vec4(col,1.0);}`;
function addWater(group){const geo=new THREE.IcosahedronGeometry(.91,5);const mat=new THREE.ShaderMaterial({uniforms:{uTime:{value:0},uColor:{value:new THREE.Color('#51ccf5')}},vertexShader:waterVertex,fragmentShader:waterFragment,roughness:.12,metalness:.12});const sphere=new THREE.Mesh(geo,mat);sphere.position.y=1.79;sphere.castShadow=true;sphere.receiveShadow=true;group.add(sphere);animationMaterials.push(mat);for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.95+i*.22,.009-i*.0015,8,128),new THREE.MeshBasicMaterial({color:i===0?0x62e8ff:0x278dac,transparent:true,opacity:.4-i*.09,blending:THREE.AdditiveBlending,depthWrite:false}));ring.position.y=1.78+(i-1)*.11;ring.rotation.set(Math.PI/2+(i-1)*.23,0,(i-1)*.4);ring.scale.set(1,1,1);group.add(ring);ring.userData.pulse=.5+i*.17;}const bubbles=new THREE.Group();for(let i=0;i<13;i++){const r=THREE.MathUtils.randFloat(.025,.072),m=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),new THREE.MeshPhysicalMaterial({color:0x95edff,transparent:true,opacity:.43,roughness:.05,metalness:.15,clearcoat:1,clearcoatRoughness:0.04}));const a=Math.random()*Math.PI*2,rr=THREE.MathUtils.randFloat(.6,1.25);m.position.set(Math.cos(a)*rr,THREE.MathUtils.randFloat(.5,3),Math.sin(a)*rr*.65);m.userData={float:THREE.MathUtils.randFloat(.2,.55),phase:Math.random()*Math.PI*2,y:m.position.y};bubbles.add(m);}group.add(bubbles);group.userData.bubbles=bubbles;}
function addEarth(group){const geo=new THREE.IcosahedronGeometry(.88,3),p=geo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i);const n=Math.sin(x*16.3+y*10.1+z*8.7)*.025+Math.sin(y*21.1-z*12.5)*.018+Math.cos(z*18.4+x*9.2)*.014;const f=1+n;p.setXYZ(i,x*f,y*f,z*f);}geo.computeVertexNormals();const rock=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0x554834,roughness:.88,metalness:.16,flatShading:true,emissive:0x19120a,emissiveIntensity:.52}));rock.position.y=1.45;rock.scale.set(1.08,1.02,.94);rock.castShadow=true;rock.receiveShadow=true;group.add(rock);
const strata=new THREE.Mesh(new THREE.TorusGeometry(.97,.036,8,96),new THREE.MeshStandardMaterial({color:0x817253,roughness:.72,metalness:.28,emissive:0x332414,emissiveIntensity:.35}));strata.position.y=1.43;strata.rotation.set(.84,.38,.25);strata.scale.set(1.02,.82,1);group.add(strata);
const cluster=new THREE.Group();const crystalMat=new THREE.MeshPhysicalMaterial({color:0x718d75,roughness:.2,metalness:.22,transmission:.08,thickness:.35,clearcoat:1,flatShading:true,emissive:0x1b3021,emissiveIntensity:.42});const crystalTips=new THREE.MeshPhysicalMaterial({color:0xc3d4b3,roughness:.15,metalness:.2,clearcoat:1,flatShading:true,emissive:0x394b35,emissiveIntensity:.48});const specs=[[-.47,-.08,.115,.45],[-.31,.24,.14,.72],[-.05,.04,.17,.91],[.2,-.21,.12,.62],[.39,.12,.14,.76],[-.03,-.35,.10,.5],[.45,-.18,.09,.46],[-.48,.19,.09,.53]];for(const [x,z,r,h] of specs){const surface=1.45+Math.sqrt(Math.max(.08,.88*.88-(x/1.08)**2-(z/.94)**2))-.04;const sh=new THREE.Mesh(new THREE.CylinderGeometry(r*.08,r,h*.7,7,1),crystalMat);sh.position.set(x,surface+h*.35,z);sh.rotation.z=THREE.MathUtils.randFloat(-.13,.13);sh.rotation.x=THREE.MathUtils.randFloat(-.1,.1);sh.castShadow=true;cluster.add(sh);const tip=new THREE.Mesh(new THREE.ConeGeometry(r*.78,h*.38,7,1),crystalTips);tip.position.set(x,surface+h*.7+h*.19,z);tip.rotation.z=sh.rotation.z*.5;tip.castShadow=true;cluster.add(tip);}group.add(cluster);
for(let i=0;i<7;i++){const boulder=new THREE.Mesh(new THREE.DodecahedronGeometry(THREE.MathUtils.randFloat(.12,.23),0),new THREE.MeshStandardMaterial({color:i%2?0x514b37:0x37382c,roughness:.95,flatShading:true}));const a=i/7*Math.PI*2;boulder.position.set(Math.cos(a)*THREE.MathUtils.randFloat(.73,1.08),THREE.MathUtils.randFloat(.48,.69),Math.sin(a)*THREE.MathUtils.randFloat(.64,.92));boulder.rotation.set(Math.random(),Math.random(),Math.random());boulder.castShadow=true;boulder.receiveShadow=true;group.add(boulder);}}

const particleVertex=`uniform float uTime;attribute float aSeed;attribute float aSize;varying float vAlpha;void main(){vec3 p=position;float t=uTime*(.22+aSeed*.12)+aSeed*6.283; p.x+=sin(t)*(.04+aSeed*.13);p.z+=cos(t*1.23)*(.04+aSeed*.13);p.y=.46+mod(position.y-.46+uTime*(.11+aSeed*.12),2.68);vAlpha=.35+.65*(.5+.5*sin(t*1.4));vec4 mv=modelViewMatrix*vec4(p,1.0);gl_PointSize=aSize*(12.0/-mv.z);gl_Position=projectionMatrix*mv;}`;
const particleFragment=`uniform vec3 uColor;varying float vAlpha;void main(){vec2 uv=gl_PointCoord-.5;float d=length(uv);float a=1.0-smoothstep(.13,.5,d);if(a<.01)discard;gl_FragColor=vec4(uColor,a*vAlpha*.68);}`;
function addMotes(group,color,count=92){const pos=new Float32Array(count*3),seed=new Float32Array(count),size=new Float32Array(count);for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,r=THREE.MathUtils.randFloat(.62,1.72);pos[i*3]=Math.cos(a)*r;pos[i*3+1]=THREE.MathUtils.randFloat(.46,3.1);pos[i*3+2]=Math.sin(a)*r*.65;seed[i]=Math.random();size[i]=THREE.MathUtils.randFloat(1.7,4.6);}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));geo.setAttribute('aSeed',new THREE.BufferAttribute(seed,1));geo.setAttribute('aSize',new THREE.BufferAttribute(size,1));const mat=new THREE.ShaderMaterial({uniforms:{uTime:{value:0},uColor:{value:new THREE.Color(color)}},vertexShader:particleVertex,fragmentShader:particleFragment,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});group.add(new THREE.Points(geo,mat));animationMaterials.push(mat);}

let activeModel=null,animationMaterials=[],active='fire',autoRotate=true,elapsed=0,targetZoom=8.25,dragging=false,lastPointerX=0;
function buildModel(id){if(activeModel){scene.remove(activeModel);activeModel.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material.dispose();}});}animationMaterials=[];activeModel=new THREE.Group();activeModel.name=`${id}-element`;activeModel.position.y=.02;scene.add(activeModel);if(id==='fire')addFire(activeModel);if(id==='air')addAir(activeModel);if(id==='water')addWater(activeModel);if(id==='earth')addEarth(activeModel);addMotes(activeModel,ELEMENTS[id].color);elementLight.color.set(ELEMENTS[id].glow);root.style.setProperty('--accent',ELEMENTS[id].color);root.style.setProperty('--accent-soft',`${ELEMENTS[id].color}1e`);document.querySelector('.viewer-frame').style.setProperty('--frame-glow',ELEMENTS[id].color);}
function setElement(id){if(!ELEMENTS[id])return;active=id;const data=ELEMENTS[id];buildModel(id);document.querySelectorAll('.rail-item').forEach(button=>{const selected=button.dataset.element===id;button.classList.toggle('is-active',selected);button.setAttribute('aria-pressed',String(selected));});document.querySelector('#info-index').textContent=data.number;document.querySelector('#info-category').textContent=data.category;document.querySelector('#element-title').innerHTML=`${data.title}<span class="title-period">.</span>`;document.querySelector('#element-subtitle').textContent=data.subtitle;document.querySelector('#element-description').textContent=data.description;document.querySelector('#property-essence').textContent=data.essence;document.querySelector('#property-polarity').textContent=data.polarity;document.querySelector('#property-state').textContent=data.state;document.querySelector('#signature-value').textContent=data.signature;document.querySelector('#element-quote').textContent=data.quote;document.querySelector('#model-caption').textContent=data.caption;document.querySelector('#stage-number').textContent=data.number;document.querySelector('#stage-progress').style.width=`${Number(data.number)*25}%`;}
setElement(active);

function resize(){const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;const width=Math.floor(rect.width),height=Math.floor(rect.height);renderer.setSize(width,height,false);composer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();bloom.setSize(width,height);}
const ro=new ResizeObserver(resize);ro.observe(canvas);window.addEventListener('resize',resize);resize();
function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-elapsed)/1000||0,.045);elapsed=now;const t=now*.001;for(const mat of animationMaterials)if(mat.uniforms?.uTime)mat.uniforms.uTime.value=t;if(activeModel){if(autoRotate&&!dragging)activeModel.rotation.y+=dt*.13;for(const child of activeModel.children){if(child.userData.spin)child.rotation.y+=dt*child.userData.spin;if(child.userData.pulse)child.scale.setScalar(1+Math.sin(t*1.25)*.025);if(child.userData.bubbles){for(const bubble of child.userData.bubbles.children){bubble.position.y=bubble.userData.y+Math.sin(t*bubble.userData.float+bubble.userData.phase)*.11;}}}}stars.rotation.y=t*.003;camera.position.z=THREE.MathUtils.lerp(camera.position.z,targetZoom,.08);composer.render(dt);}
requestAnimationFrame(animate);
document.querySelectorAll('.rail-item').forEach(button=>button.addEventListener('click',()=>setElement(button.dataset.element)));
const rotateButton=document.querySelector('#rotate-toggle');rotateButton.addEventListener('click',()=>{autoRotate=!autoRotate;rotateButton.setAttribute('aria-pressed',String(autoRotate));rotateButton.title=autoRotate?'Pause automatic rotation':'Resume automatic rotation';});
document.querySelector('#reset-view').addEventListener('click',()=>{targetZoom=8.25;if(activeModel)activeModel.rotation.set(0,0,0);});
document.querySelector('#fullscreen-toggle').addEventListener('click',async()=>{const frame=document.querySelector('.viewer-frame');if(!document.fullscreenElement){await frame.requestFullscreen?.();}else await document.exitFullscreen?.();});
canvas.addEventListener('pointerdown',event=>{dragging=true;lastPointerX=event.clientX;canvas.setPointerCapture(event.pointerId);});canvas.addEventListener('pointermove',event=>{if(!dragging||!activeModel)return;const delta=event.clientX-lastPointerX;activeModel.rotation.y+=delta*.008;lastPointerX=event.clientX;});const stopDrag=()=>{dragging=false;};canvas.addEventListener('pointerup',stopDrag);canvas.addEventListener('pointercancel',stopDrag);canvas.addEventListener('wheel',event=>{event.preventDefault();targetZoom=THREE.MathUtils.clamp(targetZoom+event.deltaY*.004,5.2,11.5);},{passive:false});
window.addEventListener('keydown',event=>{if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;const i=ORDER.indexOf(active);if(event.key==='ArrowRight')setElement(ORDER[(i+1)%ORDER.length]);if(event.key==='ArrowLeft')setElement(ORDER[(i+ORDER.length-1)%ORDER.length]);});
